Angle/Controllers/PagesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Angle.Controllers
{
    public class PagesController : Controller
    {
        public ActionResult Error_404()
        {
            return View();
        }
        public ActionResult Lock() {
            return View();
        }
        public ActionResult Login() {
            return View();
        }
        public ActionResult Recover() {
            return View();
        }
        public ActionResult Register() {
            return View();
        }
        public ActionResult Template()
        {
            return View();
        }
        public ActionResult Maintenance()
        {
            return View();
        }
        public ActionResult Error_500()
        {
            return View();
        }
    }
}

Angle/Views/Shared/_Footer.cshtml
<span>&copy; 2020 - Angle</span>

Angle/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <meta name="description" content="Bootstrap Admin App">
    <meta name="keywords" content="app, responsive, jquery, bootstrap, dashboard, admin">
    <title>Angle - Bootstrap Admin Template</title>
    <!-- =============== VENDOR STYLES ===============-->
    <link href="@Styles.Url("~/Vendor/@fortawesome/fontawesome-free/css/brands.css")" rel="stylesheet" />
    <link href="@Styles.Url("~/Vendor/@fortawesome/fontawesome-free/css/regular.css")" rel="stylesheet" />
    <link href="@Styles.Url("~/Vendor/@fortawesome/fontawesome-free/css/solid.css")" rel="stylesheet" />
    <link href="@Styles.Url("~/Vendor/@fortawesome/fontawesome-free/css/fontawesome.css")" rel="stylesheet" />
    <link href="@Styles.Url("~/Vendor/simple-line-icons/css/simple-line-icons.css")" rel="stylesheet" />
    <link href="@Styles.Url("~/Vendor/animate.css/animate.css")" rel="stylesheet" />
    <link href="@Styles.Url("~/Vendor/whirl/dist/whirl.css")" rel="stylesheet" />
    <!-- =============== PAGE VENDOR STYLES =============== -->
    @if (IsSectionDefined("Styles"))
    {@RenderSection("Styles", required: false)}
    <!-- =============== BOOTSTRAP STYLES ===============-->
    <link href="@Styles.Url("~/Content/css/bootstrap.css")" rel="stylesheet" type="text/css" id="bscss" />
    <!-- =============== APP STYLES ===============-->
    <link href="@Styles.Url("~/Content/css/app.css")" rel="stylesheet" type="text/css" id="maincss" />
    <link href="@Styles.Url("~/Content/mvc-override.css")" rel="stylesheet" type="text/css" />

</head>
<body>
    <div class="wrapper">
        <!-- top navbar-->
        <header class="topnavbar-wrapper">
            @Html.Partial("_TopNavbar")
        </header>
        <!-- sidebar-->
        <aside class="aside-container">
            @Html.Partial("_Sidebar")
        </aside>
        <!-- offsidebar-->
        <aside class="offsidebar d-none">
            @Html.Partial("_Offsidebar")
        </aside>
        <!-- Main section-->
        <section class="section-container">
            <!-- Page content-->
            <div class="content-wrapper">
                @RenderBody()
            </div>
        </section>
        <!-- Page footer-->
        <footer class="footer-container">
            @Html.Partial("_Footer")
        </footer>
    </div>
    @if (IsSectionDefined("BodyArea"))
        {@RenderSection("BodyArea", required: false)}
    <!-- =============== VENDOR SCRIPTS ===============-->
    <script src="@Scripts.Url("~/Vendor/modernizr/modernizr.custom.js")"></script>
    <script src="@Scripts.Url("~/Vendor/js-storage/js.storage.js")"></script>
    <script src="@Scripts.Url("~/Vendor/screenfull/dist/screenfull.js")"></script>
    <script src="@Scripts.Url("~/Vendor/i18next/i18next.js")"></script>
    <script src="@Scripts.Url("~/Vendor/i18next-xhr-backend/i18nextXHRBackend.js")"></script>
    <script src="@Scripts.Url("~/Vendor/jquery/dist/jquery.js")"></script>
    <script src="@Scripts.Url("~/vendor/popper.js/dist/umd/popper.js")"></script>
    <script src="@Scripts.Url("~/Vendor/bootstrap/dist/js/bootstrap.js")"></script>
    <!-- =============== PAGE VENDOR SCRIPTS ===============-->
    @RenderSection("scripts", required: false)
    <!-- =============== APP SCRIPTS ===============-->
    <script src="@Scripts.Url("~/Scripts/app.js")"></script>
</body>
</html>

Angle/Views/Shared/_LayoutHorizontal.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <meta name="description" content="Bootstrap Admin App">
    <meta name="keywords" content="app, responsive, jquery, bootstrap, dashboard, admin">
    <title>Angle - Bootstrap Admin Template</title>
    <!-- =============== VENDOR STYLES ===============-->
    <link href="@Styles.Url("~/Vendor/@fortawesome/fontawesome-free/css/brands.css")" rel="stylesheet" />
    <link href="@Styles.Url("~/Vendor/@fortawesome/fontawesome-free/css/regular.css")" rel="stylesheet" />
    <link href="@Styles.Url("~/Vendor/@fortawesome/fontawesome-free/css/solid.css")" rel="stylesheet" />
    <link href="@Styles.Url("~/Vendor/@fortawesome/fontawesome-free/css/fontawesome.css")" rel="stylesheet" />
    <link href="@Styles.Url("~/Vendor/simple-line-icons/css/simple-line-icons.css")" rel="stylesheet" />
    <link href="@Styles.Url("~/Vendor/animate.css/animate.css")" rel="stylesheet" />
    <link href="@Styles.Url("~/Vendor/whirl/dist/whirl.css")" rel="stylesheet" />
    <!-- =============== PAGE VENDOR STYLES =============== -->
    @if (IsSectionDefined("Styles"))
    {@RenderSection("Styles", required: false)}
    <!-- =============== BOOTSTRAP STYLES ===============-->
    <link href="@Styles.Url("~/Content/css/bootstrap.css")" rel="stylesheet" type="text/css" id="bscss" />
    <!-- =============== APP STYLES ===============-->
    <link href="@Styles.Url("~/Content/css/app.css")" rel="stylesheet" type="text/css" id="maincss" />
    <link href="@Styles.Url("~/Content/mvc-override.css")" rel="stylesheet" type="text/css" />

</head>
<body class="layout-h">
    <div class="wrapper">
        <!-- top navbar-->
        <header class="topnavbar-wrapper">
            @Html.Partial("_TopNavbarHorizontal")
        </header>
        <!-- offsidebar-->
        <aside class="offsidebar d-none">
            @Html.Partial("_Offsidebar")
        </aside>
        <!-- Main section-->
        <section class="section-container">
            <!-- Page content-->
            <div class="content-wrapper">
                @RenderBody()
            </div>
        </section>
        <!-- Page footer-->
        <footer class="footer-container">
            @Html.Partial("_Footer")
        </footer>
    </div>
    @if (IsSectionDefined("BodyArea"))
        {@RenderSection("BodyArea", required: false)}
    <!-- =============== VENDOR SCRIPTS ===============-->
    <script src="@Scripts.Url("~/Vendor/modernizr/modernizr.custom.js")"></script>
    <script src="@Scripts.Url("~/Vendor/js-storage/js.storage.js")"></script>
    <script src="@Scripts.Url("~/Vendor/screenfull/dist/screenfull.js")"></script>
    <script src="@Scripts.Url("~/Vendor/i18next/i18next.js")"></script>
    <script src="@Scripts.Url("~/Vendor/i18next-xhr-backend/i18nextXHRBackend.js")"></script>
    <script src="@Scripts.Url("~/Vendor/jquery/dist/jquery.js")"></script>
    <script src="@Scripts.Url("~/vendor/popper.js/dist/umd/popper.js")"></script>
    <script src="@Scripts.Url("~/Vendor/bootstrap/dist/js/bootstrap.js")"></script>
    <!-- =============== PAGE VENDOR SCRIPTS ===============-->
    @RenderSection("scripts", required: false)
    <!-- =============== APP SCRIPTS ===============-->
    <script src="@Scripts.Url("~/Scripts/app.js")"></script>
</body>
</html>

Angle/Views/Shared/_LayoutPage.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <meta name="description" content="Bootstrap Admin App">
    <meta name="keywords" content="app, responsive, jquery, bootstrap, dashboard, admin">
    <title>Angle - Bootstrap Admin Template</title>
    <!-- =============== VENDOR STYLES ===============-->
    <link href="@Styles.Url("~/Vendor/@fortawesome/fontawesome-free/css/brands.css")" rel="stylesheet" />
    <link href="@Styles.Url("~/Vendor/@fortawesome/fontawesome-free/css/regular.css")" rel="stylesheet" />
    <link href="@Styles.Url("~/Vendor/@fortawesome/fontawesome-free/css/solid.css")" rel="stylesheet" />
    <link href="@Styles.Url("~/Vendor/@fortawesome/fontawesome-free/css/fontawesome.css")" rel="stylesheet" />
    <link href="@Styles.Url("~/Vendor/simple-line-icons/css/simple-line-icons.css")" rel="stylesheet" />
    <!-- =============== PAGE VENDOR STYLES =============== -->
    @if (IsSectionDefined("Styles"))
    {@RenderSection("Styles", required: false)}
    <!-- =============== BOOTSTRAP STYLES ===============-->
    <link href="@Styles.Url("~/Content/css/bootstrap.css")" rel="stylesheet" type="text/css" id="bscss" />
    <!-- =============== APP STYLES ===============-->
    <link href="@Styles.Url("~/Content/css/app.css")" rel="stylesheet" type="text/css" id="maincss" />
</head>

<body>
    <div class="wrapper">
        @RenderBody()
    </div>
    <div class="p-lg text-center">
        <span>&copy;</span>
        <span>2016</span>
        <span>-</span>
        <span>Angle</span>
        <br>
        <span>Bootstrap Admin Template</span>
    </div>

    <!-- =============== VENDOR SCRIPTS ===============-->
    <script src="@Scripts.Url("~/Vendor/modernizr/modernizr.custom.js")"></script>
    <script src="@Scripts.Url("~/Vendor/js-storage/js.storage.js")"></script>
    <script src="@Scripts.Url("~/Vendor/screenfull/dist/screenfull.js")"></script>
    <script src="@Scripts.Url("~/Vendor/i18next/i18next.js")"></script>
    <script src="@Scripts.Url("~/Vendor/i18next-xhr-backend/i18nextXHRBackend.js")"></script>
    <script src="@Scripts.Url("~/Vendor/jquery/dist/jquery.js")"></script>
    <script src="@Scripts.Url("~/vendor/popper.js/dist/umd/popper.js")"></script>
    <script src="@Scripts.Url("~/Vendor/bootstrap/dist/js/bootstrap.js")"></script>
    <script src="@Scripts.Url("~/Vendor/parsleyjs/dist/parsley.js")"></script>
    <!-- =============== PAGE VENDOR SCRIPTS ===============-->
    @RenderSection("scripts", required: false)
    <!-- =============== APP SCRIPTS ===============-->
    <script src="@Scripts.Url("~/Scripts/app.js")"></script>
</body>

</html>

Angle/Views/Shared/_TopNavbar.cshtml
<!-- START Top Navbar-->
<nav class="navbar topnavbar">
    <!-- START navbar header-->
    <div class="navbar-header">
        <a class="navbar-brand" href="#/">
            <div class="brand-logo">
                <img class="img-fluid" src="~/Content/Images/logo.png" alt="App Logo">
            </div>
            <div class="brand-logo-collapsed">
                <img class="img-fluid" src="~/Content/Images/logo-single.png" alt="App Logo">
            </div>
        </a>
    </div>
    <!-- END navbar header-->
    <!-- START Left navbar-->
    <ul class="navbar-nav mr-auto flex-row">
        <li class="nav-item">
            <!-- Button used to collapse the left sidebar. Only visible on tablet and desktops-->
            <a class="nav-link d-none d-md-block d-lg-block d-xl-block" href="#" data-trigger-resize="" data-toggle-state="aside-collapsed">
                <em class="fas fa-bars"></em>
            </a>
            <!-- Button to show/hide the sidebar on mobile. Visible on mobile only.-->
            <a class="nav-link sidebar-toggle d-md-none" href="#" data-toggle-state="aside-toggled" data-no-persist="true">
                <em class="fas fa-bars"></em>
            </a>
        </li>
        <!-- START User avatar toggle-->
        <li class="nav-item d-none d-md-block">
            <!-- Button used to collapse the left sidebar. Only visible on tablet and desktops-->
            <a class="nav-link" id="user-block-toggle" href="#user-block" data-toggle="collapse">
                <em class="icon-user"></em>
            </a>
        </li>
        <!-- END User avatar toggle-->
        <!-- START lock screen-->
        <li class="nav-item d-none d-md-block">
            <a class="nav-link" href="@Url.Action("Lock", "Pages")" title="Lock screen">
                <em class="icon-lock"></em>
            </a>
        </li>
        <!-- END lock screen-->
    </ul>
    <!-- END Left navbar-->
    <!-- START Right Navbar-->
    <ul class="navbar-nav flex-row">
        <!-- Search icon-->
        <li class="nav-item">
            <a class="nav-link" href="#" data-search-open="">
                <em class="icon-magnifier"></em>
            </a>
        </li>
        <!-- Fullscreen (only desktops)-->
        <li class="nav-item d-none d-md-block">
            <a class="nav-link" href="#" data-toggle-fullscreen="">
                <em class="fa fa-expand"></em>
            </a>
        </li>
        <!-- START Alert menu-->
        <li class="nav-item dropdown dropdown-list">
            <a class="nav-link dropdown-toggle dropdown-toggle-nocaret" href="#" data-toggle="dropdown">
                <em class="icon-bell"></em>
                <span class="badge badge-danger">11</span>
            </a>
            <!-- START Dropdown menu-->
            <div class="dropdown-menu dropdown-menu-right animated flipInX">
                <div class="dropdown-item">
                    <!-- START list group-->
                    <div class="list-group">
                        <!-- list item-->
                        <div class="list-group-item list-group-item-action">
                            <div class="media">
                                <div class="align-self-start mr-2">
                                    <em class="fab fa-twitter fa-2x text-info"></em>
                                </div>
                                <div class="media-body">
                                    <p class="m-0">New followers</p>
                                    <p class="m-0 text-muted text-sm">1 new follower</p>
                                </div>
                            </div>
                        </div>
                        <!-- list item-->
                        <div class="list-group-item list-group-item-action">
                            <div class="media">
                                <div class="align-self-start mr-2">
                                    <em class="fa fa-envelope fa-2x text-warning"></em>
                                </div>
                                <div class="media-body">
                                    <p class="m-0">New e-mails</p>
                                    <p class="m-0 text-muted text-sm">You have 10 new emails</p>
                                </div>
                            </div>
                        </div>
                        <!-- list item-->
                        <div class="list-group-item list-group-item-action">
                            <div class="media">
                                <div class="align-self-start mr-2">
                                    <em class="fa fa-tasks fa-2x text-success"></em>
                                </div>
                                <div class="media-body">
                                    <p class="m-0">Pending Tasks</p>
                                    <p class="m-0 text-muted text-sm">11 pending task</p>
                                </div>
                            </div>
                        </div>
                        <!-- last list item-->
                        <div class="list-group-item list-group-item-action">
                            <span class="d-flex align-items-center">
                                <span class="text-sm">More notifications</span>
                                <span class="badge badge-danger ml-auto">14</span>
                            </span>
                        </div>
                    </div>
                    <!-- END list group-->
                </div>
            </div>
            <!-- END Dropdown menu-->
        </li>
        <!-- END Alert menu-->
        <!-- START Offsidebar button-->
        <li class="nav-item">
            <a class="nav-link" href="#" data-toggle-state="offsidebar-open" data-no-persist="true">
                <em class="icon-notebook"></em>
            </a>
        </li>
        <!-- END Offsidebar menu-->
    </ul>
    <!-- END Right Navbar-->
    <!-- START Search form-->
    <form class="navbar-form" role="search" action="search.html">
        <div class="form-group">
            <input class="form-control" type="text" placeholder="Type and hit enter ...">
            <div class="fa fa-times navbar-form-close" data-search-dismiss=""></div>
        </div>
        <button class="d-none" type="submit">Submit</button>
    </form>
    <!-- END Search form-->
</nav>
<!-- END Top Navbar-->

Angle/Views/Shared/_TopNavbarHorizontal.cshtml
<!-- START Top Navbar-->
<nav class="navbar topnavbar navbar-expand-lg navbar-light">
    <!-- START navbar header-->
    <div class="navbar-header">
        <a class="navbar-brand" href="#/">
            <div class="brand-logo">
                <img class="img-fluid" src="~/Content/Images/logo.png" alt="App Logo">
            </div>
            <div class="brand-logo-collapsed">
                <img class="img-fluid" src="~/Content/Images/logo-single.png" alt="App Logo">
            </div>
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#topnavbar">
            <span class="navbar-toggler-icon"></span>
        </button>
    </div>
    <!-- END navbar header-->
    <!-- START Nav wrapper-->
    <div class="navbar-collapse collapse" id="topnavbar">
        <!-- START Left navbar-->
        <ul class="nav navbar-nav mr-auto flex-column flex-lg-row">
            <li class="nav-item dropdown @Html.isActive(controller: "Dashboard")">
                <a class="nav-link dropdown-toggle dropdown-toggle-nocaret" href="#dashboard" data-toggle="dropdown">Dashboard</a>
                <div class="dropdown-menu animated fadeIn">
                    <a class="dropdown-item @Html.isActive("Dashboard", "Dashboard_v1")" href="@Url.Action("Dashboard_v1", "Dashboard")">Dashboard v1</a>
                    <a class="dropdown-item @Html.isActive("Dashboard", "Dashboard_v2")" href="@Url.Action("Dashboard_v2", "Dashboard")">Dashboard v2</a>
                    <a class="dropdown-item @Html.isActive("Dashboard", "Dashboard_v3")" href="@Url.Action("Dashboard_v3", "Dashboard")">Dashboard v3</a>
                </div>
            </li>
            <li class="nav-item @Html.isActive(controller: "Widgets")">
                <a class="nav-link" href="@Url.Action("Index", "Widgets")">Widgets</a>
            </li>
        </ul>
        <!-- END Left navbar-->
        <!-- START Right Navbar-->
        <ul class="navbar-nav flex-row">
            <!-- START lock screen-->
            <li class="nav-item">
                <a class="nav-link" href="@Url.Action("Lock", "Pages")" title="Lock screen">
                    <em class="icon-lock"></em>
                </a>
            </li>
            <!-- END lock screen-->
            <!-- Search icon-->
            <li class="nav-item">
                <a class="nav-link" href="#" data-search-open="">
                    <em class="icon-magnifier"></em>
                </a>
            </li>
            <!-- Fullscreen (only desktops)-->
            <li class="nav-item d-none d-md-block">
                <a class="nav-link" href="#" data-toggle-fullscreen="">
                    <em class="fa fa-expand"></em>
                </a>
            </li>
            <!-- START Alert menu-->
            <li class="nav-item dropdown dropdown-list">
                <a class="nav-link dropdown-toggle dropdown-toggle-nocaret" href="#" data-toggle="dropdown">
                    <em class="icon-bell"></em>
                    <span class="badge badge-danger">11</span>
                </a>
                <!-- START Dropdown menu-->
                <div class="dropdown-menu dropdown-menu-right animated flipInX">
                    <div class="dropdown-item">
                        <!-- START list group-->
                        <div class="list-group">
                            <!-- list item-->
                            <div class="list-group-item list-group-item-action">
                                <div class="media">
                                    <div class="align-self-start mr-2">
                                        <em class="fab fa-twitter fa-2x text-info"></em>
                                    </div>
                                    <div class="media-body">
                                        <p class="m-0">New followers</p>
                                        <p class="m-0 text-muted text-sm">1 new follower</p>
                                    </div>
                                </div>
                            </div>
                            <!-- list item-->
                            <div class="list-group-item list-group-item-action">
                                <div class="media">
                                    <div class="align-self-start mr-2">
                                        <em class="fa fa-envelope fa-2x text-warning"></em>
                                    </div>
                                    <div class="media-body">
                                        <p class="m-0">New e-mails</p>
                                        <p class="m-0 text-muted text-sm">You have 10 new emails</p>
                                    </div>
                                </div>
                            </div>
                            <!-- list item-->
                            <div class="list-group-item list-group-item-action">
                                <div class="media">
                                    <div class="align-self-start mr-2">
                                        <em class="fa fa-tasks fa-2x text-success"></em>
                                    </div>
                                    <div class="media-body">
                                        <p class="m-0">Pending Tasks</p>
                                        <p class="m-0 text-muted text-sm">11 pending task</p>
                                    </div>
                                </div>
                            </div>
                            <!-- last list item-->
                            <div class="list-group-item list-group-item-action">
                                <span class="d-flex align-items-center">
                                    <span class="text-sm">More notifications</span>
                                    <span class="badge badge-danger ml-auto">14</span>
                                </span>
                            </div>
                        </div>
                        <!-- END list group-->
                    </div>
                </div>
                <!-- END Dropdown menu-->
            </li>
            <!-- END Alert menu-->
            <!-- START Offsidebar button-->
            <li class="nav-item">
                <a class="nav-link" href="#" data-toggle-state="offsidebar-open" data-no-persist="true">
                    <em class="icon-notebook"></em>
                </a>
            </li>
            <!-- END Offsidebar menu-->
        </ul>
        <!-- END Right Navbar-->
    </div>
    <!-- END Nav wrapper-->
    <!-- START Search form-->
    <form class="navbar-form" role="search" action="search.html">
        <div class="form-group">
            <input class="form-control" type="text" placeholder="Type and hit enter ...">
            <div class="fa fa-times navbar-form-close" data-search-dismiss=""></div>
        </div>
        <button class="d-none" type="submit">Submit</button>
    </form>
    <!-- END Search form-->
</nav>
<!-- END Top Navbar-->